### ISSUE TITLE
Option to disable/enable refresh on save.

### ISSUE THREAD

**Issue by christophernilsson** [kevin-mueller/HtmlCssClassCompletion#15]
It would be great if there existed an option to disable or enable the "refresh on save for .html and .css". On large projects, every time I save, it takes a few seconds (5s to 10s) to refresh. During this time, visual studio is "froozen". By having this option, I can choose when I want to re-scan.

Otherwise, nice work!!

**Comment by kevin-mueller** [comment]
Good idea! It has been implemented with the latest release. Please update the extension to 1.15. :)
