### ISSUE TITLE
Does this extension override the default extension in VS2022?

### ISSUE THREAD

**Issue by rlebowitz** [kevin-mueller/HtmlCssClassCompletion#16]
I have recently started working with Tailwind and thought it would be useful to have an extension that could display the various class names and a short description of their functionality.  Does your extension override the default one used in VS2022, or could you have multiple extensions which display CSS classes from various sources?  

Yours is the only example I've found that shows how to build an extension of this sort; kudos on the work you've done.

**Comment by kevin-mueller** [comment]
The default intellisense of VS still works, if thats what you mean. This Extension only replaces the intellisense when you are in a _class=_ context. :)
