### ISSUE TITLE
Update when deleting css files

### ISSUE THREAD

**Issue by AMUCOMO** [kevin-mueller/HtmlCssClassCompletion#3]
I noticed, after installing the extension I don't get any suggestions any more at all (not even the few measly buggy ones).
But after SCANNING I get them all. That's nice, since VS is extremely buggy and inconsistent (I get different suggestions each time I open VS and mostly BS is missing - w/o the extension).
But I noticed, when I delete a .css file, the suggestions stick - even after re-scanning. Only after closing VS, re-open and re-scan, it's correct again.
Also, when re-naming or deleting classes inside a css file, it's the same. RE-scanning w/o closing does not remove invalidated classes from the suggestion.

**Comment by AMUCOMO** [comment]
IDK if this has to do with the extension or with VS, but I found  very peculiar behavior. I get different suggestions, depending on, whether I simply place the caret inside the `""` of an existing `<... class="" ...>` then I will get only the suggestions from the .css in the static wwwroot folder (but not those from the isolated files). However, if I am typing the entire attribute 'class' or when I place the caret inside the "" but I delete the three characters (like deleting `s="`  ) and then retyping it (so the for VS the attribute is newly created) then I actually get ONLY the suggestions from isolated .css files ... Cheez, what is going on, VS is so buggy.

EDIT:
I tested the same with disabled extension. The test is ofc unreliable, as is VS itself (very inconsistent). But the result is, that w/o extension I seem to get only my self written isolated classes as suggestions. So basically I can access all suggestions, by deliberately deciding on deleting the leading `"` in the `class=""` or not. Ofc it would be nicer, if I would always get all suggestions, or even better only those from the isolated css that is actually valid. I'm still happy that this extension exists, since I think it's actually Microsoft's job to make VS more usable in this regard. :)

"oi" is the class from open-iconic, which comes with the default project template for blazor and is in the wwwroot. "whyyy" is from my isolated css file Index.razor.css. The code is written in Index.razor.

![ezgif-2-05a22e4a99](https://user-images.githubusercontent.com/90450913/165297254-920a9aad-dc2d-4b4f-b1f3-ba1702b86a75.gif)

EDIT 2:
This seems only to be true for Index.razor. In all other pages/components, it actually works as expected! (suggestions simply by entering the "", no deleting, and getting only VALID isolated css and static css classes. IDK why the index page is an exception (same folder and everything).

**Comment by kevin-mueller** [comment]
Thank you for your extensive testing, and for using the extension! 
I will look at those issues as soon as possible (probably this weekend). I think they all are solvable.

Stay tuned for updates! :)

**Comment by kevin-mueller** [comment]
Issues tracked here:
#4 
#5 
#6

**Comment by kevin-mueller** [comment]
The issues should be fixed in the latest version 1.1. Thanks for bringing them to my attention @AMUCOMO!
