### ISSUE TITLE
Renaming / deleting classes requires restart of VS to correctly remove them from the suggestion cache.

### ISSUE THREAD

**Issue by kevin-mueller** [kevin-mueller/HtmlCssClassCompletion#5]
When renaming or deleting a CSS class, the suggestion stays in the cache, even if manually re-scanned.

**Comment by AMUCOMO** [comment]
Works well. I noticed another minor particularity.
It seems like the extension load classes from
a) any .css class in the project (which is not a razor.css)
b) any isolated css classes (for example Index.razor.css for Index.razor)
I accidentally made a typo and the isolated css file was not case-sensitive compared to the page (index.razor.css with a lower case "i")... This file's classes were not scanned. IDK right now, how default VS behavior in general is for such wrong-case isolated classes or code-behind files, but at least the solution explorer visually seems to recognize them correctly. I'd consider it a mistake/bad practice not the match case here, anyway, but it's simply sth i noticed. (IDK if that has implications in other places, but if not, and if VS in general accepts different casing here, it would be more consistent if the extension would do that also.)

**Comment by kevin-mueller** [comment]
You're right, case should be ignored when checking for isolated context. 
Issue tracked here: #7

**Comment by kevin-mueller** [comment]
Fixed in version 1.11
@AMUCOMO
