### ISSUE TITLE
Extension doesn't work at all

### ISSUE THREAD

**Issue by silverferrum** [kevin-mueller/HtmlCssClassCompletion#8]
I'm lucky to get this popup open after starting to rescan.
![image](https://user-images.githubusercontent.com/19478181/171472825-3b3e9c74-c323-4c6b-86bf-e931d2720d33.png)

Visual Studio 2022 Community
Blazor Project

**Comment by kevin-mueller** [comment]
Very strange. Not sure what causes this. Do you have any special characters in the path to either your project, or your default NuGet folder? (where your NuGet packages are installed to).

I think it's because of that, as this error message generally occurs when creating a new FileInfo object with an invald path in its constructor.
@silverferrum

**Comment by silverferrum** [comment]
I've made *.css search in my solution folder

![image](https://user-images.githubusercontent.com/19478181/171573282-82e558f4-4ec2-4ea4-8fb4-fd29c22f76cc.png)

Seems there is nothing extraordinary with file names or with paths.

But with a clean project, it works fine.

Maybe you just will skip a file instead of throwing an error?

**Comment by kevin-mueller** [comment]
@silverferrum Please download the latest version. I hope it fixes it for you.
https://github.com/kevin-mueller/HtmlCssClassCompletion/releases/tag/1.12

(Or simply download/update from the marketplace)

**Comment by silverferrum** [comment]
It didn't help :(
An error hasn't been shown.
@kevin-mueller maybe you could make debug version for me with extended error details?

**Comment by kevin-mueller** [comment]
@silverferrum You can try to debugg it yourself. Just select the "Visual Studio Extension Development" option in the Visual Studio Installer and you should be able to just start the project once you've cloned it.

**Comment by silverferrum** [comment]
[Okay](https://youtube.com/clip/UgkxiW0uvw__DrD5a6fr7_AvTela365a5TMp)
